### ISSUE TITLE
Tossing an error for dragonflight - Can this be updated?

### ISSUE THREAD

**Issue by greenstones** [Xruptor/xanAchievementMover#1]
Message: ...e/AddOns/xanAchievementMover/xanAchievementMover.lua:99: attempt to index global 'UIPARENT_MANAGED_FRAME_POSITIONS' (a nil value)
Time: Wed Oct 26 09:55:45 2022
Count: 1
Stack: ...e/AddOns/xanAchievementMover/xanAchievementMover.lua:99: attempt to index global 'UIPARENT_MANAGED_FRAME_POSITIONS' (a nil value)

Locals:

**Comment by Xruptor** [comment]
It looks like they just disabled and reworked a lot of their code to break addons. Why am I not surprised. They do this every patch and every expansion. I'll take a look at it, but without an active account this will be interesting.  I'll take a look, it seems they changed their global frame variables.

**Comment by azuraji** [comment]
Yep that's what I've always hated about the game. Blizz expect players to be tech savvy so that they can fix all the broken addons themselves. They don't show much regard for the player base :/

Anyway, I think you can create a low level character and test out the addon. They've completely removed `UIPARENT_MANAGED_FRAME_POSITIONS` but I'm not sure how frames are positioned instead.

**Comment by azuraji** [comment]
I always keep a few characters below level 20 so I can test addons in case I haven't played for awhile and don't have an active subscription :)

**Comment by Xruptor** [comment]
Hmm this probably has a lot to do with it.
https://worldofwarcraft.com/en-us/news/23837944/get-into-the-grid-of-things-with-the-updated-ui-and-hud

I'll see about getting my PTR and or low level free toon working.  But this addon may be obsolete now.  I'll have to take a look.

**Comment by G4il1** [comment]
Just wanted to give a comment: 
I have played around a bit with the new Edit mode however one of the few things I have not been able to move is the Achievement / Dungeon alert window and it keeps popping up over the moved action bars :-(
Might be I am missing something but If you are able to fix this it would be much appreciated.

**Comment by Xruptor** [comment]
Yep I noticed they didn't add it to their code.  Seems odd they added everything except those alert popups.  I'll have to take a look at the code.  They have changed the window management all over the place.

**Comment by Xruptor** [comment]
Okay it looks like they completely updated their Alert Systems.... again.  So I'll need to see how they are being generated and fired before I can actually move the AchievementFrame.

https://github.com/tomrus88/BlizzardInterfaceCode/blob/e2b884c714b3e751a9ec84b89a5fda964f35da05/Interface/FrameXML/AlertFrameSystems.lua

Examples of changes:
`
LootAlertFrame 

LootAlertSystem = AlertFrame:AddQueuedAlertFrameSubSystem("LootWonAlertFrameTemplate", LootWonAlertFrame_SetUp, 6, math.huge);


AchievementAlertSystem = AlertFrame:AddQueuedAlertFrameSubSystem("AchievementAlertFrameTemplate", AchievementAlertFrame_SetUp, 2, 6);
AchievementAlertSystem:SetCanShowMoreConditionFunc(function() return not C_PetBattles.IsInBattle() end);`

**Comment by G4il1** [comment]
Thanks for looking into it and hopefully you will get it solved.

**Comment by azuraji** [comment]
@Xruptor I'm looking through the changes but can't find anything specific that would resolve the bugs? Which particular issue did you fix to make it work?

**Comment by Xruptor** [comment]
> @Xruptor I'm looking through the changes but can't find anything specific that would resolve the bugs? Which particular issue did you fix to make it work?

I removed UIPARENT_MANAGED_FRAME_POSITIONS from running on Retail as it's no longer used.  It is STILL used however in WOTLK Classic.  This was the primary issue. In terms of the AlertSystem API, I thought I had to rewrite code because they changed a few things for Dragonflight.  However, when I inspected the code on the PTR and WOTL_PTR it worked fine when I performed some tests.  So not much was necessary in order for it to function properly.

If you are still getting errors, you will need to be a bit more specific.  Which version of WOW are you using and what exactly is the error you are getting.  Please file a new ticket if you do have continued issues.  That way I can track it there, rather then follow this ticket.

**Comment by Xruptor** [comment]
> @Xruptor I'm looking through the changes but can't find anything specific that would resolve the bugs? Which particular issue did you fix to make it work?

@azuraji 
I removed UIPARENT_MANAGED_FRAME_POSITIONS from running on Retail as it's no longer used.  It is STILL used however in WOTLK Classic.  This was the primary issue. In terms of the AlertSystem API, I thought I had to rewrite code because they changed a few things for Dragonflight.  However, when I inspected the code on the PTR and WOTL_PTR it worked fine when I performed some tests.  So not much was necessary in order for it to function properly.

If you are still getting errors, you will need to be a bit more specific.  Which version of WOW are you using and what exactly is the error you are getting.  Please file a new ticket if you do have continued issues.  That way I can track it there, rather then follow this ticket.

**Comment by azuraji** [comment]
> > @Xruptor I'm looking through the changes but can't find anything specific that would resolve the bugs? Which particular issue did you fix to make it work?
> 
> @azuraji I removed UIPARENT_MANAGED_FRAME_POSITIONS from running on Retail as it's no longer used. It is STILL used however in WOTLK Classic. This was the primary issue. In terms of the AlertSystem API, I thought I had to rewrite code because they changed a few things for Dragonflight. However, when I inspected the code on the PTR and WOTL_PTR it worked fine when I performed some tests. So not much was necessary in order for it to function properly.
> 
> If you are still getting errors, you will need to be a bit more specific. Which version of WOW are you using and what exactly is the error you are getting. Please file a new ticket if you do have continued issues. That way I can track it there, rather then follow this ticket.

Awesome, thanks for the detailed answer. I'll make sure to file an issue if I run into any future bugs 🥳

**Comment by Xruptor** [comment]
> > > @Xruptor I'm looking through the changes but can't find anything specific that would resolve the bugs? Which particular issue did you fix to make it work?
> > 
> > 
> > @azuraji I removed UIPARENT_MANAGED_FRAME_POSITIONS from running on Retail as it's no longer used. It is STILL used however in WOTLK Classic. This was the primary issue. In terms of the AlertSystem API, I thought I had to rewrite code because they changed a few things for Dragonflight. However, when I inspected the code on the PTR and WOTL_PTR it worked fine when I performed some tests. So not much was necessary in order for it to function properly.
> > If you are still getting errors, you will need to be a bit more specific. Which version of WOW are you using and what exactly is the error you are getting. Please file a new ticket if you do have continued issues. That way I can track it there, rather then follow this ticket.
> 
> Awesome, thanks for the detailed answer. I'll make sure to file an issue if I run into any future bugs 🥳

Sure thing any time.  Glad I was able to help.  😄
